version = 1

test_patterns = [
    "dask/**/test_*.py",
    "dask/**/*_test.py"
]

exclude_patterns = [
    "continuous_integration/**",
    "docs/**"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "black"
enabled = true
